# SATELLITES module
# TODO: DRY it one day
indexSuccess:
  javascripts: ['controllers/e_satellites_index.js']

hostSuccess:
  javascripts: ['http://maps.google.com/maps/api/js?libraries=places&sensor=false', 'libs/scriptaculous-controls.js', 'libs/colorpicker.js', 'libs/formmap.js', 'controllers/e_satellites_host_edit.js']

editSuccess: 
  javascripts: ['http://maps.google.com/maps/api/js?libraries=places&sensor=false', 'libs/scriptaculous-controls.js', 'libs/colorpicker.js', 'libs/formmap.js', 'controllers/e_satellites_host_edit.js']

createSuccess:
  javascripts: ['http://maps.google.com/maps/api/js?libraries=places&sensor=false', 'libs/scriptaculous-controls.js', 'libs/colorpicker.js', 'libs/formmap.js', 'controllers/e_satellites_host_edit.js']

updateSuccess:
  javascripts: ['http://maps.google.com/maps/api/js?libraries=places&sensor=false', 'libs/scriptaculous-controls.js', 'libs/colorpicker.js', 'libs/formmap.js', 'controllers/e_satellites_host_edit.js']
