generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Press
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          press
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing

    config:
      actions: ~
      fields:  ~
      list:
        table_method: getWithPosition
        display: ['_position', =title, media, date]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
