# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:

  melody:
    create_user: false
    remember_user: true
    redirect_register: @loggedin

    eventbrite:
      key: DZ3QWRJQG75Z2K7QQ7
      secret: 5JSC5HEBQQIPAL7SBWOQQ3XME3CKGYSDK7NMTJAJLJOSEFO7UP
      callback: @homepage
      provider: eventbrite
      request_auth_url: https://www.eventbrite.com/oauth/authorize
      access_token_url: https://www.eventbrite.com/oauth/token

#      scope: [email]
#      user:
#        username:
#          call: user_get
#          path: user.user_id
#          prefix: Eventbrite_
#        first_name:
#          call: user_get
#          path: user.first_name
#        last_name:
#          call: user_get
#          path: user.last_name
#        email_address:
#          call: user_get
#          path: user.email
#          key: true
