# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Tech Open Air Berlin | This is NOT Europe's SXSW | Tech, Music, Art & Science | August 1-2, 2013
    description:  TOA is a 2 two-day festival that aim to connect, grow and inspire the creative, entrepreneurial and scientific community through knowledge exchange and collaboration.
    #keywords:     TOA, Tech Open Air, Festival, Unconference
    language:     en
    #robots:       index, follow

  stylesheets:    ['main.css?killcache2']

  javascripts:    ['http://use.typekit.net/ios4gyb.js', 'libs/prmtoaculous-1.9.0p1.7.1.micro.js', 'libs/protoScrollSpy.js', 'controllers/e_common.js']

  has_layout:     true
  layout:         layout
