generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Program
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          program
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing

    config:
      actions: ~
      fields:
        url:
          help: The website address without http:// prefix
        facebook:
          help: Plain facebook profile name, without http://facebook.com/ prefix
        twitter:
          help: Twitter username, without @ or http://twitter.com/ prefix
      list:
        display: [=title, =start_hour, =end_hour]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
