generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Speaker
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          speaker
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing

    config:
      actions: ~
      fields:  ~
      list:
        table_method: getWithPosition
        display: ['_position', '_face', =first_name, =last_name, company_position, company]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
