press:
  class: sfDoctrineRouteCollection
  options:
    model:                Press
    module:               press
    prefix_path:          /press
    column:               id
    with_wildcard_routes: true

attendee:
  class: sfDoctrineRouteCollection
  options:
    model:                Attendee
    module:               attendee
    prefix_path:          /attendee
    column:               id
    with_wildcard_routes: true

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               user
    prefix_path:          /user
    column:               id
    with_wildcard_routes: true

organiser:
  class: sfDoctrineRouteCollection
  options:
    model:                Organiser
    module:               organiser
    prefix_path:          /organiser
    column:               id
    with_wildcard_routes: true

event:
  class: sfDoctrineRouteCollection
  options:
    model:                Event
    module:               event
    prefix_path:          /event
    column:               id
    with_wildcard_routes: true

category:
  class: sfDoctrineRouteCollection
  options:
    model:                Category
    module:               category
    prefix_path:          /category
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
#  param: { module: default, action: index }
  param: { module: sfAdminDash, action: dashboard }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
